# -*- coding: utf-8 -*-
"""downloadnltk_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qt-tx8xCZkFzmIpGlFu5zDsneP1yvTKd
"""

import nltk
nltk.download('stopwords')